In [4]:
import numpy as np 
import pandas as pd 
df = pd.read_csv(r"C:\Users\KEERTHI SRI S\OneDrive\Desktop\AI_Data_Journey\2Months_of_ML\mini projects\insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
df.info() 
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
df = pd.get_dummies(df, drop_first=True)
df.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False

In [7]:
X = df.drop("charges", axis=1)
y = df["charges"]
print(X.head())
print(y.head())

   age     bmi  children  sex_male  smoker_yes  region_northwest  \
0   19  27.900         0     False        True             False
1   18  33.770         1      True       False             False
2   28  33.000         3      True       False             False
3   33  22.705         0      True       False              True
4   32  28.880         0      True       False              True

   region_southeast  region_southwest
0             False              True
1              True             False
2              True             False
3             False             False
4             False             False
0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(1070, 8)
(268, 8)

In [9]:
from sklearn.linear_model import LinearRegression 
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [11]:
y_pred = model.predict(X_test)
print(y_pred[:5]) 
print(y_test[:5].values)

[ 8969.55027444  7068.74744287 36858.41091155  9454.67850053
 26973.17345656]
[ 9095.06825  5272.1758  29330.98315  9301.89355 33750.2918 ]

In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("MAE:", mae)
print("RMSE:", rmse)

MAE: 4181.194473753652
RMSE: 5796.2846592762735

In [13]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

In [14]:
from sklearn.metrics import mean_absolute_error
rf_mae = mean_absolute_error(y_test, rf_pred)
print("Random Forest MAE:", rf_mae)

Random Forest MAE: 2575.596333170865

In [15]:
import pickle
with open("model.pkl", "wb") as f:
    pickle.dump(rf, f)
with open("columns.pkl", "wb") as f:
    pickle.dump(X.columns, f)